name: "Get Version Number Components"
description: "Gets the version number compoents (i.e. major, minor, patch, build, revision, and suffix) from supplied version JSON string."
author: "Teq Bench"

# Define your inputs here.
inputs:
  INPUT_UPDATE_TYPE:
    type: string
    required: true
    description: "Type of version update. Options: MAJOR, MINOR, PATCH."
  INPUT_VERSION_JSON:
    type: string
    required: true
    description: "JSON string containing version data."

# Define your outputs here.
outputs:
  major:
    description: "Major version component"
  minor:
    description: "Minor version component"
  patch:
    description: "Patch version component"
  build:
    description: "Build version component"
  revision:
    description: "Revision version component"
  suffix:
    description: "Suffix version component"
  version:
    description: "Four part version number: major.minor.build.revision"
  tag:
    description: "Four part version number with 'v' prefix"
    
runs:
  using: node20
  main: dist/index.js
