name: "Get Version Number Components"
description: "Gets the version number compoents (i.e. major, minor, patch, build, revision, and suffix) from supplied version JSON string."
author: "Teq Bench"

# Define your inputs here.
inputs:
  INPUT_VERSION_JSON:
    required: true
    description: "JSON string containing version data."

# Define your outputs here.
outputs:
  major:
    description: "Major version component"
  minor:
    description: "Minor version component"
  patch:
    description: "Patch version component"
  build:
    description: "Build version component"
  revision:
    description: "Revision version component"
  suffix:
    description: "Suffix version component"

runs:
  using: node20
  main: dist/index.js
