name: "Get Version Number Components"
description: "Gets the version number compoents (i.e. major, minor, patch, build, revision, and suffix) from supplied version JSON string."
author: "Teq Bench"

# Define your inputs here.
inputs:
  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
