name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          version-json: '{"major":31,"minor":1,"patch":0,"build":457,"revision":0,"suffix":"alpha"}'

      - name: Print Output
        id: output
        run: |
          echo "major version = ${{ steps.test-action.outputs.major }}"
          echo "minor version = ${{ steps.test-action.outputs.minor }}"
          echo "patch version = ${{ steps.test-action.outputs.patch }}"
          echo "build version = ${{ steps.test-action.outputs.build }}"
          echo "revision version = ${{ steps.test-action.outputs.revision }}"
          echo "suffix version = ${{ steps.test-action.outputs.suffix }}"
          
